on:
  push:
    branches:
      - main

name: CI

jobs:
  cargo_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install nasm
        uses: ilammy/setup-nasm@v1
        if: startsWith(matrix.os, 'windows')
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --exclude reweb3-num --exclude futures-quic --exclude xstack-kad
